const token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlMDRiYjJjNjRhOWI3MjJjMDJhZjUxNyIsImlhdCI6OTU3MzU1NjU0OSwiZXhwIjoxOTc2MTQ4NTQ5fQ.leMN1m-70gG04CLCBpFhctpZTZ7ekZqyfeidBtAbeGQ'

exports.bearerToken = `Bearer ${token}`